// Auto-generated from the original Thailes iOS source (CharacterLookup.m).
// Consonant class is authoritative: mid/high lists from determineConsonantClass; all others are low.
const CONSONANTS = [
  { cp: 3585, ch: "ก", cls: "mid", name: "ko kai" },
  { cp: 3586, ch: "ข", cls: "high", name: "kho khai" },
  { cp: 3587, ch: "ฃ", cls: "high", name: "kho khuat" },
  { cp: 3588, ch: "ค", cls: "low", name: "kho khwai" },
  { cp: 3589, ch: "ฅ", cls: "low", name: "kho khon" },
  { cp: 3590, ch: "ฆ", cls: "low", name: "kho ra-khang" },
  { cp: 3591, ch: "ง", cls: "low", name: "ngo ngu" },
  { cp: 3592, ch: "จ", cls: "mid", name: "cho chan" },
  { cp: 3593, ch: "ฉ", cls: "high", name: "cho ching" },
  { cp: 3594, ch: "ช", cls: "low", name: "cho chang" },
  { cp: 3595, ch: "ซ", cls: "low", name: "so so" },
  { cp: 3596, ch: "ฌ", cls: "low", name: "cho choe" },
  { cp: 3597, ch: "ญ", cls: "low", name: "yo ying" },
  { cp: 3598, ch: "ฎ", cls: "mid", name: "do cha-da" },
  { cp: 3599, ch: "ฏ", cls: "mid", name: "to pa-tak" },
  { cp: 3600, ch: "ฐ", cls: "high", name: "tho than" },
  { cp: 3601, ch: "ฑ", cls: "low", name: "tho montho" },
  { cp: 3602, ch: "ฒ", cls: "low", name: "tho phu-thao" },
  { cp: 3603, ch: "ณ", cls: "low", name: "no nen" },
  { cp: 3604, ch: "ด", cls: "mid", name: "do dek" },
  { cp: 3605, ch: "ต", cls: "mid", name: "to tao" },
  { cp: 3606, ch: "ถ", cls: "high", name: "tho thung" },
  { cp: 3607, ch: "ท", cls: "low", name: "tho thahan" },
  { cp: 3608, ch: "ธ", cls: "low", name: "tho thong" },
  { cp: 3609, ch: "น", cls: "low", name: "no nu" },
  { cp: 3610, ch: "บ", cls: "mid", name: "bo baimai" },
  { cp: 3611, ch: "ป", cls: "mid", name: "po pla" },
  { cp: 3612, ch: "ผ", cls: "high", name: "pho phueng" },
  { cp: 3613, ch: "ฝ", cls: "high", name: "fo fa" },
  { cp: 3614, ch: "พ", cls: "low", name: "pho phan" },
  { cp: 3615, ch: "ฟ", cls: "low", name: "fo fan" },
  { cp: 3616, ch: "ภ", cls: "low", name: "pho sam-phao" },
  { cp: 3617, ch: "ม", cls: "low", name: "mo ma" },
  { cp: 3618, ch: "ย", cls: "low", name: "yo yak" },
  { cp: 3619, ch: "ร", cls: "low", name: "ro ruea" },
  { cp: 3621, ch: "ล", cls: "low", name: "lo ling" },
  { cp: 3623, ch: "ว", cls: "low", name: "wo waen" },
  { cp: 3624, ch: "ศ", cls: "high", name: "so sala" },
  { cp: 3625, ch: "ษ", cls: "high", name: "so ruesi" },
  { cp: 3626, ch: "ส", cls: "high", name: "so suea" },
  { cp: 3627, ch: "ห", cls: "high", name: "ho hip" },
  { cp: 3628, ch: "ฬ", cls: "low", name: "lo chula" },
  { cp: 3629, ch: "อ", cls: "mid", name: "o ang" },
  { cp: 3630, ch: "ฮ", cls: "low", name: "ho nok-huk" },
];
